language: node_js
node_js:
    - "node"
services:
  - postgresql
notifications:
    email: false
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
script:
    - npm test && npm run coverage
after_success:
    - codecov
addons:
  postgresql: "9.5"
services:
  - redis-server
.
